### ISSUE TITLE
$help full color

### ISSUE THREAD

**Issue by mortifia** [UnionRolistes/Bot_Base#20]

**Comment by S2P-KB** [comment]
Il semblerait que le code initial prévoyait des couleurs et d'autres choses pour le résultat de commande **$help**. Cependant, le résultat est différent. Ci-dessous deux screens.

![Image](https://github.com/UnionRolistes/Bot_Base/assets/154507882/86d33818-5d18-4133-b809-7df00c6af40d)



![Image](https://github.com/UnionRolistes/Bot_Base/assets/154507882/a68e7aeb-c356-48c1-b9bf-89290d21b263)
