### ISSUE TITLE
Refaire la documentation de Bot_Base

### ISSUE THREAD

**Issue by younesbourakadi** [UnionRolistes/Bot_Base#41]

**Comment by S2P-KB** [comment]
La documentation est déjà re-faîte grâce à la branche #9 . Dans le besoin où il faudrait y ajouter quelque chose d'autre, et en sachant que l'objectif à terme est de centraliser les informations sur le README.md de **Bot_Base** (#58 ), je pense qu'on peut fermer ce ticket.
