### ISSUE TITLE
Modifier l'app icon, le nom et la description du bot programmatiquement

### ISSUE THREAD

**Issue by younesbourakadi** [UnionRolistes/Bot_Base#50]
L'utilisateur doit pouvoir changer l'app icon, le nom et le description via le code python

**Comment by younesbourakadi** [comment]
https://stackoverflow.com/questions/72383303/change-discord-bot-profile-picture-with-command-in-python

**Comment by Fr-Dae** [comment]
**Name:** UR-Bot
**Icon:** 
![Hydre-blanc](https://github.com/UnionRolistes/Bot_Base/assets/23202421/fbc37215-738f-4b88-9ca8-3f118ca75368)

**Description:** 
- Documentation, https://github.com/UnionRolistes/Bot_Base
- From http://unionrolistes.fr/,

**Comment by Fr-Dae** [comment]
Au lancement, envoyer une commande qui définie les valeurs, name, icone, description en fonction de notre modele.
